const CONFIG = {
    CANVAS_WIDTH: 500,
    CANVAS_HEIGHT: 400,
    INITIAL_MONEY: 50,
    INITIAL_CASTLE_HEALTH: 100,
    PATH_WIDTH: 20,
    BULLET_SPEED: 5,
    ENEMY_SPAWN_INTERVAL: 1000,
    COUNTDOWN_DURATION: 3,
    ENEMIES_PER_WAVE: 10
};
